### ISSUE TITLE
Crashes when minify enabled on Android

### ISSUE THREAD

**Issue by fredpedersen** [realm/realm-kotlin-samples#23]
This sample app, when minify is set to true in the android build.gradle.kts crashes on startup with the following error:

/Users/realm/workspace-realm-kotlin/releases/packages/cinterop/src/jvm/jni/java_class.cpp:49: [realm-core-11.15.0] Assertion failed: cls with (class_name) =  ["io/realm/internal/interop/sync/NetworkTransport"]

**Comment by nhachicha** [comment]
Hi @fredpedersen which sample app are you using? The [Bookshelf](https://github.com/realm/realm-kotlin-samples/tree/main/Bookshelf)  uses minify and it works?

**Comment by rorbech** [comment]
Closing this due to lack of input. @fredpedersen If this is still an issue please provide some details about which sample and explicit gradle step that fails.

**Comment by itopenup** [comment]
Hi, I have the same issue.
Android, Realm 1.5.0, minification enabled
-keep class io.realm.kotlin.internal.interop.NativePointer { *; } is there
